<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AsortymentSuszuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsortymentSuszuRepository extends \Doctrine\ORM\EntityRepository
{
    public function podajAsortymentSuszu()
    {
        return $this -> createQueryBuilder('asortyment_suszu') //W funkcji podaj nazwe tabeli w bazie danych
            ->orderBy('asortyment_suszu.asortyment', 'ASC'); //Podaj kolumne w tabeli
    }
}