<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * DaneSuszeniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaneSuszeniaRepository extends \Doctrine\ORM\EntityRepository
{

    public function raportSuszenia()
    {

        $conn = $this->getEntityManager()->getConnection();
        
        $sql = "SELECT * FROM dane_suszenia ";
        $stmt = $conn->prepare($sql);
      //  $stmt->bindValue(1, $id);
        $stmt->execute();
        
        return $stmt->fetchAll();
       // var_dump($stmt->fetchAll());die;
        //return json_encode($wynik);

    }
    
}