<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9yfemzc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9yfemzc/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9yfemzc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9yfemzc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9yfemzc\appProdProjectContainer(array(
    'container.build_hash' => '9yfemzc',
    'container.build_id' => '347807fa',
    'container.build_time' => 1517158064,
));
