<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMal3egy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMal3egy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMal3egy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMal3egy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMal3egy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mal3egy',
    'container.build_id' => '21b384e7',
    'container.build_time' => 1517157070,
));
