<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJvtqjxs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJvtqjxs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJvtqjxs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJvtqjxs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJvtqjxs\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jvtqjxs',
    'container.build_id' => '77ad0f10',
    'container.build_time' => 1520171992,
));
