<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcturmr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcturmr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXcturmr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXcturmr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXcturmr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xcturmr',
    'container.build_id' => 'b39543b4',
    'container.build_time' => 1519759240,
));
